language: node_js
node_js:
    - 10.23.0
branchrs:
    only:
    - master
script:
    - echo "Beginning docker build"
    - docker build -t udagram-frontend .
    - docker tag udagram-frontend renjithtech6/udgaram-frontend

after_success:
    - echo "About to create container in Docker registry"
    - echo "$D_PSWD" | docker login -u "$D_UNAME" --password-stdin
    - docker push renjithtech6/udagram-frontend
